# .github/workflows/docker-latest.yml
name: Auto Build & Push Docker Image (latest)

on:
  schedule:
    - cron: '0 11 * * 2'   # 9pm Tuesday AEST (AEST is UTC+10, so 11:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: chrisjbawden/opencanary-ui:latest
