# .github/workflows/publish-package.yml
name: Publish Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version/tag to publish (e.g., 1.0.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
        # If you need the tag/version in the package metadata, make sure your setup.py/setup.cfg uses it.
